config/routes.rb
Jobseekers::Application.routes.draw do
  resources :categories

  resources :employments

  resources :educations

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "jobs", to: "pages#jobs", as: "jobs"
  get "jobs/:id", to: "pages#show_job", as: "job"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "jobs/drafts", to: "jobs#drafts", as: "jobs_drafts"
    get "jobs/dashboard", to: "jobs#dashboard", as: "jobs_dashboard"
    resources :jobs
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  enum job_length: [:permanent, :temporary, :contract]
  enum job_type: [:full_time, :part_time]

  before_save { MarkdownWriter.update_html(self) }

  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :content_md, presence: true
  validates :keywords, format: {with: /\A([[:alnum:]]+)(,\s*[[:alnum:]]+)*\z/i,
                                message: "can contain only numbers and letters and must be separated by a comma."}

  paginates_per 30

  belongs_to :user
  belongs_to :category
  has_many :applications

  scope :published, lambda { where(draft: false).order("updated_at DESC") }
  scope :drafted, lambda { where(draft: true).order("updated_at DESC") }
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController

  before_action :set_job, only: [
    :edit,
    :update,
    :destroy
  ]


  def dashboard
    @published_job_count = Job.published.count
    @draft_job_count = Job.drafted.count
  end

  def index
    @jobs = Job.published.page(params[:page]).per(50)
  end

  def drafts
    @jobs = Job.drafted.page(params[:page]).per(50)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params.merge!(user: current_user))
    @job.user_id = current_user.id
    if @job.save
      redirect_to admin_jobs_dashboard_path, notice: "New job published."
    else
      flash[:alert] = "Job not published."
      render :new
    end
  end

  def edit
  end

  def update
    @job.slug = nil
    if @job.update(job_params.merge!(user: current_user))
      redirect_to admin_jobs_dashboard_path, notice: "Job successfully edited."
    else
      flash[:alert] = "The job was not edited."
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to admin_jobs_path, notice: "The job has been deleted."
  end


  private

  def set_job
    @job = Job.where(user: current_user).friendly.find(params[:id])
  end

  def job_params
    params.require(:job).permit(
      :title,
      :content_md,
      :draft,
      :updated_at,
      :keywords,
      :city,
      :job_length,
      :job_type,
      :suitable_for_graduates,
      :category_id,
      :salary,
      :reference
    )
  end


end

app/views/admin/jobs/_form.html.erb
<% if @job.errors.any? %>
<ul>
  <% @job.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [:admin, @job], role: "form" do |f| %>

<div class="form-group">
  <%= f.label :title %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_field :title, :autofocus => true, class: "form-control monospaced-control", placeholder: "Title (also used for URL slug)..." %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :content_md, "Content" %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_area :content_md, rows: 15, class: "form-control monospaced-control", placeholder: "Job content (Markdown format)..." %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :category_id, 'Category' %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, class: "form-control monospaced-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :city %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.select :city,
                    grouped_options_for_select(City.groupedlist),
                    {},
                    {class: "form-control"} %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :job_length, 'Job length and type' %>
  <div class="row">
    <div class="col-xs-1">
      <%= f.select :job_length, Job.job_lengths.keys.to_a.map { |w| [w.humanize, w] }, class: "form-control monospaced-control" %>
    </div>
    <div class="col-xs-1">
      <%= f.select :job_type, Job.job_types.keys.to_a.map { |w| [w.humanize, w] }, class: "form-control monospaced-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-xs-12">
      <%= f.check_box :suitable_for_graduates %> <%= f.label :draft, "Suitable for graduates?" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :keywords %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_field :keywords, class: "form-control monospaced-control", placeholder: "pre-school, mornings, Math" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :salary %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.number_field :salary, class: "form-control monospaced-control" %>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label :reference %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.text_field :reference, class: "form-control monospaced-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 padded">
    <button class='btn btn-primary'>
      <i class='fa fa-plus-square'></i> Publish
    </button> - <%= link_to "Cancel", admin_jobs_dashboard_path %>
  </div>
</div>

<% end %>

app/views/admin/jobs/dashboard.html.erb
<% title("Jobs Dashboard") %>
<h3 class="page-title">Jobs <small>Dashboard</small></h3>
<p><%= link_to "Back to Admin", admin_root_path %></p>
<hr/>
<div class="row">
  <div class="col-sm-4">Published: <%= link_to "#{pluralize(@published_job_count, 'job')}", admin_jobs_path %></div>
  <div class="col-sm-4">Drafts: <%= link_to "#{pluralize(@draft_job_count, 'draft')}", admin_jobs_drafts_path %></div>
  <div class="col-sm-4"><%= link_to "New job", new_admin_job_path %></div>
</div>

app/views/admin/jobs/drafts.html.erb
<% title("Job Drafts") %>
<h3 class="page-title">Jobs <small>Drafts</small></h3>
<p><%= link_to "Back to dashboard", admin_jobs_dashboard_path %></p>
<hr/>

<p class="pagination-summary"><%= page_entries_info @jobs %></p>
<%= paginate @jobs %>

<hr/>

<ul class="fa-ul">
  <% @jobs.each do |job| %>
  <li class="margin-md-down">
    <i class="fa fa-arrow-circle-o-right small"></i>&nbsp;&nbsp;
    <%= link_to job.title, edit_admin_job_path(job.slug) %> <br/>
    <small class="x-small-text">about <%= time_ago_in_words(job.updated_at) %> ago</small>
  </li>
  <% end %>
</ul>

<hr/>

<%= paginate @jobs %>

app/views/admin/jobs/edit.html.erb
<% title("Edit #{@job.title}") %>
<h3 class="page-title">Edit job <small><%= @job.title %></small></h3>
<p>
  <%= link_to "Back to dashboard", admin_jobs_dashboard_path %>
</p>
<hr/>

<%= render 'form' %>
<hr/>
<%= link_to "<i class='fa fa-minus-square'></i> Delete job".html_safe, admin_job_path(@job), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-small btn-danger" %>

app/views/admin/jobs/index.html.erb
<% title("Published jobs") %>
<h3 class="page-title">Jobs <small>Published</small></h3>
<p><%= link_to "Back to dashboard", admin_jobs_dashboard_path %></p>
<hr/>

<p class="pagination-summary"><%= page_entries_info @jobs %></p>
<%= paginate @jobs %>

<hr/>

<ul class="fa-ul">
  <% @jobs.each do |job| %>
  <li class="margin-md-down">
    <i class="fa fa-arrow-circle-o-right small"></i>&nbsp;&nbsp;
    <%= link_to job.title, edit_admin_job_path(job.slug) %> <br/>
    <small class="x-small-text">about <%= time_ago_in_words(job.updated_at) %> ago</small>
  </li>
  <% end %>
</ul>

<hr/>

<%= paginate @jobs %>

app/views/admin/jobs/new.html.erb
<% title("New job") %>
<h3 class="page-title">Add a new job</h3>
<p><%= link_to "Back to dashboard", admin_jobs_dashboard_path %></p>
<hr/>

<%= render 'form' %>