config/routes.rb
Jobseekers::Application.routes.draw do
  resources :categories

  resources :employments

  resources :educations

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  get "jobs", to: "pages#jobs", as: "jobs"
  get "jobs/:id", to: "pages#show_job", as: "job"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "jobs/drafts", to: "jobs#drafts", as: "jobs_drafts"
    get "jobs/dashboard", to: "jobs#dashboard", as: "jobs_dashboard"
    resources :jobs
  end

end

app/views/pages/contact.html.erb
<% title("Contact") %>
<h1 class="page-title">Contact</h1>

<div class="row">
  <div class="col-sm-6">

    <%= form_tag email_confirmation_path, method: 'job', html: {role: "form"} do %>

    <div class="form-group">
      <%= label_tag :name, "Your name" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_field_tag :name, @name, placeholder: "Enter your name...", :autofocus => true, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :email, "Your email" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_field_tag :email, @email, placeholder: "Enter your email...", class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :message, "Your message" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_area_tag :message, @message, placeholder: "Enter your message...", rows: 10, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 padded">
        <button class='btn btn-primary'>
          <i class='fa fa-envelope'></i> Send
        </button>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1><i class="fa fa-home"></i> JobSeekers

app/views/pages/inside.html.erb
<% title("Your resume") %>
<h1>Your resume</h1>

<h2>Profile <small><%= link_to 'edit', edit_user_registration_path %></small></h2>
<p>Email: <%= current_user.email %></p>
<p>First name: <%= current_user.first_name %></p>
<p>Last name: <%= current_user.last_name %></p>
<p>Country: <%= ISO3166::Country.find_country_by_alpha2(current_user.country).try(:name) || current_user.country %></p>
<p>City: <%= current_user.city %></p>
<p>LinkedIn URL: <%= current_user.linkedin_url %></p>
<p>Facebook URL: <%= current_user.facebook_url %></p>
<p>Twitter URL: <%= current_user.twitter_url %></p>
<p>Google+ URL: <%= current_user.google_plus_url %></p>

<h2>Education <small><%= link_to 'add an entry', new_education_path %></small></h2>
<% if current_user.educations.count == 0 %>
  No entries yet, <%= link_to 'add one!', new_education_path %>
<% else %>
  <% current_user.educations.order(start_date: :desc).each do |education| %>
    <p>
      <h4>
        <%= education.name %>
        <small> <%= link_to 'edit', edit_education_path(education) %></small>
        <small>| <%= link_to 'remove', education, method: :delete, data: { confirm: 'Are you sure you want to remove this education?' } %></small>
      </h4>
    </p>
    <p> Start date: <%= education.start_date %></p>
    <p> End date: <%= education.end_date %></p>
    <p> Institution: <%= education.institution %></p>
    <p> Grade: <%= education.grade %></p>
    <p> Description: <%= education.description %></p>
  <% end %>
<% end %>

<h2>Job experience <small><%= link_to 'add an entry', new_employment_path %></small></h2>
<% if current_user.employments.count == 0 %>
  No entries yet, <%= link_to 'add one!', new_employment_path %>
<% else %>
  <% current_user.employments.each do |employment| %>
    <p>
      <h4>
        <%= employment.title %>
        <small> <%= link_to 'edit', edit_employment_path(employment) %></small>
        <small>| <%= link_to 'remove', employment, method: :delete, data: { confirm: 'Are you sure you want to remove this employment?' } %></small>
      </h4>
    </p>
    <p> Start date: <%= employment.start_date %></p>
    <p> End date: <%= employment.end_date %></p>
    <p> Description: <%= employment.description %></p>
    <p> Key skills: <%= employment.key_skills %></p>
  <% end %>
<% end %>

app/views/pages/jobs.html.erb
<% title("Jobs") %>
<h1>Jobs</h1>

<% @jobs.each do |job| %>

<div class="title-box">
  <p>
    <%= link_to "#{job.title}", job_path(job.slug) %> <br/>
    <span><small><em><%= time_ago_in_words(job.updated_at) %> ago</em></small></span>
  </p>

</div>

<% end %>

<div class="pagination-control text-center">
  <%= paginate @jobs %>
</div>

app/views/pages/show_job.html.erb
<div class="row">
  <div class="col-sm-3">
    <h2><%= @job.title %></h2>
    <p><%= @job.user_id %></p>
    <p><b>Keywords:</b><br> <%= @job.keywords %></p>
    <p><b>City:</b><br> <%= @job.city %></p>
    <p><b>Job type:</b> <%= @job.job_length.humanize %>, <%= @job.job_type.humanize %></p>
    <% if @job.suitable_for_graduates %>
      <p><b>Suitable for graduates:</b> ✓</p>
    <% end %>
    <p><b>Category:</b> <%= @job.category.name %></p>
    <p><b>Salary:</b> <%= number_to_currency(@job.salary, unit: '£', precision: 0) %></p>
    <p><b>Reference:</b> <%= @job.reference %></p>
    <h3><small><i class="fa fa-calendar"></i>&nbsp;&nbsp;<%= @job.updated_at.strftime("%Y, %B %-d") %></small></h3>
  </div>
  <div class="col-sm-9"><%= @job.content_html.html_safe %></div>
</div>